#!/bin/sh

#create documents and variables

touch lineDiffOriginal.txt
deleted=0
added=0
lineAt=0
URL=""
currentDate=`date`

#get what user it is. I will be using a test text file for now.
if [[ ! -f lineDiff.txt ]]
then
    echo `git config --list` >> lineDiff.txt
sed -i 's/.*user.name=/username: /g' lineDiff.txt
sed -i 's/user.email=/email: /g' lineDiff.txt
sed -i 's/core.editor.*//g' lineDiff.txt
fi




#get all of the changes made
echo `git diff --numstat HEAD~` > lineDiffOriginal.txt

#get all files and save them into a txt file
echo `git ls-tree -r --name-only master` > allFiles.txt

#get rid of the files that were edited.
sed -i 's/.txt//g' lineDiffOriginal.txt
sed -i 's|[a-zA-Z]*||g' lineDiffOriginal.txt

#add required numbers together.

while IFS= read -r line; do
	#echo "text of in Diff: $line" > lineDiff.txt
	IFS=' ' read -r -a array <<< "$line"
	
	#echo "deleted is: $deleted added is: $added index is: $lineAt" >> lineDiff.txt
	
	for i in "${array[@]}"
do
	#echo "at line" $lineAt >> lineDiff.txt 
	#echo $i >> lineDiff.txt
	if (( $lineAt%2 == 0 )); then
		#echo "add them together in added" >> lineDiff.txt
		let "added=$added+$i"
	else
		#echo "add them together in delted" >> lineDiff.txt
		let "deleted=$deleted+$i"
	fi
	
	let "lineAt=$lineAt+1"
	
done
	
done < lineDiffOriginal.txt

#create URL for the given commit.

echo `git config --list` > lineDiffOriginal.txt
sed -i 's/.*remote.origin.url=/URL: /g' lineDiffOriginal.txt
sed -i 's/\.git.*/\/commit\//g' lineDiffOriginal.txt
URL=`cat lineDiffOriginal.txt`

echo `git rev-parse HEAD` > lineDiffOriginal.txt
URL+=`cat lineDiffOriginal.txt`

#get the watermark, and check how many of each different watermark for every file ********in progress******
while IFS= read -r line
do
	#go to file location in line
	#echo "text of line in allFiles: $line" >> lineDiff.txt
	while IFS= read -r fileLine
	do
	
	#loop through every line in location looking for "wm:"
	
	#if find wm: on first find of every watermark, save the watermark and keep track of how many of those are found
	
	#add all of the watermarks up, and count how many are in the array[watermark][how many]
	
	#exit this function
	done < $line

done < allFiles.txt


#print out all the information ******need to add watermarks*******
echo "added: $added deleted: $deleted		$currentDate		$URL" >> lineDiff.txt
rm lineDiffOriginal.txt
