#!/usr/bin/env python3

import argparse, os, re, random, string
from hashlib import sha256

# Declare globals
directory: str = ""
email: str = ""
asn_no: str = ""
watermark_code: str = ""

def generate_watermark() -> str:
    letters = string.ascii_lowercase
    salt = ''.join(random.choice(letters) for i in range(5))
    bsalt = salt.encode('utf-8')
    basnno = asn_no.encode('utf-8')
    bemail = email.encode('utf-8')
    return sha256(basnno + bemail + bsalt).hexdigest()

def watermark_file(path: str):
    print("-> Searching " + path + " for watermarkable lines...", end="")
    wf = open(path, "r+")
    lineNo: int = 0
    watermarks: int = 0
    for line in wf:
        lineNo += 1
        if "aw:watermark" in line:
            print("ln" + str(lineNo) + "...", end="")
            watermarks += 1
            line.replace("aw:watermark", "aw:" + watermark_code)

    if watermarks == 0:
        print("no watermarks found.")
    else:
        print("done.")
    
    wf.close()

def main():
    parser = argparse.ArgumentParser(description="Watermark files specified in " + \
        "an .acesfile and zip the folder.")
    parser.add_argument("directory", type=str, help="directory with a .acesfile")
    parser.add_argument("email", type=str, help="student email for watermarking")
    parser.add_argument("asn_no", type=str, help="assignment identifier (i.e. Asn1)")
    args = parser.parse_args()

    if not os.path.isdir(args.directory):
        print("Error: directory does not exist.")
        exit(1)

    if not os.path.exists(args.directory + "/.acesfile"):
        print("Error: no .acesfile found in directory.")
        exit(1)

    email_regex = re.compile("(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")
    if not email_regex.match(args.email):
        print("Error: email argument is not an email address.")
        exit(1)

    directory = args.directory
    email = args.email
    asn_no = args.asn_no
    watermark_code = generate_watermark()

    print("Generated watermark: " + watermark_code)

    print("Watermarking " + directory + " with " + email + "...")
    acesfile = open(directory + "/.acesfile", "r")
    for line in acesfile:
        line = str.rstrip(line)
        markablefile = directory + "/" + line
        if os.path.exists(markablefile):
            watermark_file(markablefile)
    acesfile.close()

    pass

if __name__ == "__main__":
    main()