var searchData=
[
  ['aces',['ACES',['../namespace_a_c_e_s.html',1,'']]],
  ['aces_5fgui',['ACES_GUI',['../namespace_a_c_e_s___g_u_i.html',1,'']]],
  ['addreasonwhy',['addReasonWhy',['../class_a_c_e_s_1_1_student.html#a707f7de9a6f937224976fe53d4c1087f',1,'ACES::Student']]],
  ['analyzer',['Analyzer',['../class_a_c_e_s_1_1_analyzer.html',1,'ACES.Analyzer'],['../class_a_c_e_s_1_1_analyzer.html#ab7c2eb5b8037bf11e8a9b9ee58ebf416',1,'ACES.Analyzer.Analyzer()']]],
  ['analyzer_2ecs',['Analyzer.cs',['../_analyzer_8cs.html',1,'']]],
  ['app',['App',['../class_a_c_e_s_1_1_app.html',1,'ACES']]],
  ['app_2eg_2ecs',['App.g.cs',['../_app_8g_8cs.html',1,'']]],
  ['app_2eg_2ei_2ecs',['App.g.i.cs',['../_app_8g_8i_8cs.html',1,'']]],
  ['app_2examl_2ecs',['App.xaml.cs',['../_app_8xaml_8cs.html',1,'']]],
  ['assemblyinfo_2ecs',['AssemblyInfo.cs',['../_assembly_info_8cs.html',1,'']]],
  ['author',['Author',['../class_a_c_e_s_1_1_git_commit.html#afd61148ff5a5132aa23530a1650455a7',1,'ACES::GitCommit']]],
  ['avgstddev',['AvgStdDev',['../class_a_c_e_s_1_1_class_room.html#aacf7a0bbdcfc4ff30c6b54bd15cfcc20',1,'ACES::ClassRoom']]],
  ['avgtimebetweencommits',['AvgTimeBetweenCommits',['../class_a_c_e_s_1_1_student.html#a5ca3c11e30f2c940807d092e8150d371',1,'ACES::Student']]],
  ['createclass',['CreateClass',['../namespace_a_c_e_s___g_u_i_1_1_create_class.html',1,'ACES_GUI']]],
  ['properties',['Properties',['../namespace_a_c_e_s_1_1_properties.html',1,'ACES']]],
  ['userlogin',['UserLogin',['../namespace_a_c_e_s_1_1_user_login.html',1,'ACES']]]
];
