#!/bin/sh

#create variables
touch lineDiff.txt
touch lineDiffOriginal.txt
deleted=0
added=0
lineAt=0


#get all of the changes made
echo `git diff --numstat HEAD~` > lineDiffOriginal.txt
cp lineDiffOriginal.txt lineDiff.txt

#get rid of the files that were edited.
sed -i 's/.txt//g' lineDiffOriginal.txt
sed -i 's|[a-zA-Z]*||g' lineDiffOriginal.txt

#add required numbers together.

while IFS= read -r line; do
	#echo "text of in Diff: $line" > lineDiff.txt
	IFS=' ' read -r -a array <<< "$line"
	
	#echo "deleted is: $deleted added is: $added index is: $lineAt" >> lineDiff.txt
	
	for i in "${array[@]}"
do
	#echo "at line" $lineAt >> lineDiff.txt 
	#echo $i >> lineDiff.txt
	if (( $lineAt%2 == 0 )); then
		#echo "add them together in added" >> lineDiff.txt
		let "added=$added+$i"
	else
		#echo "add them together in delted" >> lineDiff.txt
		let "deleted=$deleted+$i"
	fi
	
	let "lineAt=$lineAt+1"
	
done
	
	
	
done < lineDiffOriginal.txt

echo "added: $added deleted: $deleted" > lineDiff.txt
rm lineDiffOriginal.txt